name: boiling_flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - matplotlib
  - Pillow>=9.1
  - scipy
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-book-theme
  - ruamel.yaml
  - psutil
  - pip  # Add any additional packages here and in pyproject.toml
  - pip:
      - -e .